export default function getTickerCode() {
  return {
    ticker: {
      aim: `"TICKER Symbol","Company Name"
"SPA","1Spatial Holdings"
"4BB","4basebio Plc"
"4GBL","4global"
"88E","88 Energy"
"ABDP","AB Dynamics"
"ABDX","Abingdon Healt."
"ACC","Access Intelligence"
"ACSO","Accesso Technology Group"
"ACRL","Accrol Gp"
"AXS","Accsys Tech"
"AEG","Active Energy"
"AOM","Activeops"
"ACRM","Acuity Rm Grp"
"ADME","Adm Energy"
"AMS","Advanced Medical Solutions Group"
"AFN","ADVFN"
"AEO","Aeorema Comm."
"AFC","AFC Energy"
"AET","Afentra Plc."
"AFRN","Aferian"
"ANIC","Agronomics"
"AIEA","AIREA"
"ALBA","Alba Mineral Resources"
"UFO","Alien Metals"
"APH","Alliance Pharma"
"AFM","Alpha Financial Markets Consulting"
"ALPH","Alpha Group International"
"ALT","Altitude Group"
"ALU","Alumasc Group"
"AMRQ","Amaroq Minerals"
"ATM","Andrada Mining."
"ASY","Andrew Sykes"
"ANX","Anexo Group Plc"
"AGL","Angle"
"AYM","Anglesey Mining"
"ANG","Angling Direct"
"AAZ","Anglo Asian"
"ANGS","Angus Energy"
"ANCR","Animalcare Grp"
"ANP","Anpario"
"APTA","Aptamer Group"
"AQX","Aquis Exchange"
"ARBB","Arbuthnot"
"ARCM","Arc Minerals"
"ARC","Arcontech Group"
"AREC","Arecor Therape"
"AGFX","Argentex Group."
"ARGO","Argo Group"
"AAU","Ariana"
"ARK","Arkle Res"
"ACP","Armadale Capital"
"AXL","Arrow Explor."
"ARV","Artemis Res"
"ART","Artisanal Sp.co"
"AST","Ascent Resources"
"AT.","Ashtead Technology"
"ARS","Asiamet Res"
"ASTO","Assetco"
"ATYM","Atalaya Mining"
"ALL","Atlantic Lithium"
"ATOM","Atome Plc"
"BOOM","Audioboom Grp."
"AUK","Aukett Swanke"
"AURA","Aura Egy"
"AUTG","Autins Group"
"AVCT","Avacta Group"
"AVG","Avingtrans"
"BPM","B.p Marsh"
"B90","B90 Holdings"
"BGO","Bango"
"BOIL","Baron Oil"
"BSE","Base Resources"
"BKS","Beeks Fin.cloud"
"BEG","Begbies"
"BELL","Belluscura"
"BEN","Bens Creek"
"BEM","Beowulf"
"BZT","Bezant Res"
"BIDS","Bidstack Group"
"BIG","Big Technologies"
"BBB","Bigblu Broadb."
"BILN","Billington"
"BIOM","Biome Tech"
"BVXP","Bioventix"
"BVX","Bivictrix Thera"
"BIRD","Blackbird"
"BLOE","Block Energy P."
"BLU","Blue Star"
"JAY","Bluejay"
"BOKU","Boku"
"BOO","Boohoo"
"BOR","Borders &amp; Sth."
"BOD","Botswana Diam"
"BLVN","Bowleven"
"BHL","Bradda Head Lithium"
"BAR","Brand Architek."
"BBSN","Brave Bison"
"BRH","Braveheart Inv"
"BRCK","Brickability Group"
"PIER","Brighton Pier"
"BRK","Brooks Macdonald"
"BWNG","Brown Group"
"BUR","Burford Capital"
"BMN","Bushveld Minerals"
"BYOT","Byotrol"
"C4XD","C4x Discry Hdgs"
"KDNC","Cadence Mineral"
"CBOX","Cake Box Holdi."
"CMCL","Caledonia Min"
"CLX","Calnex Solutio."
"CNSL","Cambr Nutri Sci"
"COG","Cambridge Cog"
"CAM","Camellia"
"CPX","Cap-xx"
"CMET","Capital Metals"
"CASP","Caspian Sunrise"
"CTAI","Catenai Plc"
"CAV","Cavendish Fin"
"CEL","Celadon Pharma."
"CLBS","Celebrus Tech"
"CLA","Celsius Res"
"CAML","Central Asia Metals"
"CER","Cerillion"
"CEG","Challenger Energy"
"CMH","Chamberlin &amp; Hill"
"CCT","Character"
"CHAR","Chariot Ltd"
"CKT","Checkit"
"CTG","Christie"
"CHH","Churchill China"
"CPH2","Clean Power Hyd"
"CTL","Cleantech Lithium"
"CLON","Clontarf"
"CLCO","Cloudcoco"
"CML","CML Microcircuits"
"CMO","Cmo Group"
"CHRT","Cohort"
"COM","Comptoir Grp"
"CNC","Concurrent Technologies"
"CNR","Condor Gold"
"CGNR","Conroy Gld&amp;nres"
"CIC","Conygar Inv"
"CORA","Cora Gold"
"CRU","Coral Products"
"CRCL","Corcel"
"CRDL","Cordel Group"
"CNS","Corero Network"
"CSFS","Cornerstone Fs"
"CUSN","Cornish Metals."
"CORO","Coro Energy"
"CPP","Cppgroup"
"CRW","Craneware"
"CREO","Creo Medical"
"TIDE","Crimson Tide"
"CSSG","Croma Security"
"CRPR","Cropper (J)"
"CRS","Crystal Amber"
"CTA","Ct Automotive"
"CVSG","CVS Group"
"CYAN","Cyanconnode"
"DCI","Dci Advisors"
"DKL","Dekel Agri"
"DEMG","Deltex Medical"
"DELT","Deltic Energy"
"IGR","Design Group"
"DEST","Destiny Pharma."
"DEVO","Devolver Dig. S"
"DWHT","Dewhurst"
"DWHA","Dewhurst A"
"DXRX","Diaceutics"
"DNM","Dianomi"
"DBOX","Digitalbox"
"DSG","Dillistone"
"DCTA","Directa Plus"
"DIS","Distil"
"DOTD","dotDigital Group"
"DPP","Dp Poland"
"DRV","Driver Grp"
"DSW","Dsw Capital"
"DUKE","Duke Capital"
"ETX","E-therapeutics"
"EYE","Eagle Eye"
"EBQ","Ebiquity"
"ECK","Eckoh Technologies"
"ECO","Eco (atlantic)"
"EAH","Eco Animal"
"ECOB","Eco Buildings"
"ECR","ECR Minerals"
"EDEN","Eden"
"EAAS","Eenergy Group"
"EKF","Ekf Diagnostics"
"ELCO","Elecosoft"
"ELIX","Elixirr International"
"EML","Emmerson"
"EEE","Empire Metals"
"EMR","Empresaria Group"
"EME","Empyrean"
"ETP","Eneraqua Tech"
"EXR","Engage Xr"
"ENSI","Ensilica"
"NTQ","Enteq Tech"
"ESO","Epe Special Opp"
"EPWN","Epwin Grp"
"EQT","Eqtec"
"EQLS","Equals Gp"
"ESYS","Essensys"
"ENET","Ethernity Net"
"EUA","Eurasia Mining"
"EUZ","Europa Metals"
"EOG","Europa Oil &amp; Gas"
"EMH","European Metals Holdings"
"EMAN","Everyman Media"
"EVG","Evgen Pharma"
"ADF","Facilities Adf"
"FOG","Falcon Oil"
"FARN","Faron Pharma"
"FDP","FD Technologies"
"FDBK","Feedback"
"FEVR","Fevertree"
"BANK","Fiinu"
"FTC","Filtronic"
"FNTL","Fintel"
"FA.","Fireangel"
"FRG","Firering Strat"
"FPO","First Property"
"FLO","Flowtech Fluid."
"TUNE","Focusrite"
"FNX","Fonix"
"FRAN","Franchise Brands"
"FEN","Frenkel Topping"
"FDEV","Frontier Dev"
"FIPP","Frontier Ip"
"FRP","Frp Advisory Group"
"FMET","Fulcrum Metals"
"FAB","Fusion Antibody"
"FUM","Futura Medical"
"FME","Future Metals"
"GAL","Galantas Gold"
"GLR","Galileo Resourc"
"GMAA","Gama Aviation"
"GMR","Gaming Realms"
"GAMA","Gamma Communications"
"GTLY","Gateley Holdings"
"GATC","Gattaca"
"GBG","Gb Group"
"GCM","GCM Resources"
"G4M","Gear4music"
"GELN","Gelion"
"GEM","Gemfields Grou."
"GDR","Genedrive"
"GENI","Genincode"
"GETB","Getbusy"
"GTC","Getech Grp"
"GFIN","Gfinity"
"GBP","Global Petroleum"
"DATA","GlobalData"
"GMET","Golden Metal Re"
"GDP","GoldPlat"
"GHH","Gooch &amp; Housego"
"GOOD","Good Enrg"
"GRC","Grc Intl"
"GWMO","Great Western"
"GGP","Greatland Gold"
"GRP","Greencoat Renewables"
"GROC","Greenroc Mining"
"GFM","Griffin Mining"
"GUN","Gunsynd"
"HAT","H&amp;t Group Plc"
"HDD","Hardide"
"HSP","Hargreaves Serv"
"HARL","Harland &amp; Wolff"
"HMI","Harvest Mi (di)"
"HAYD","Haydale"
"HUW","Helios Underw"
"HE1","Helium One"
"HERC","Hercules Site"
"HZM","Horizonte Minerals"
"HRN","Hornby"
"HSS","Hss Hire"
"HUD","Huddled Group"
"HUM","Hummingbird"
"HCM","Hutchmed"
"HVO","hVIVO"
"IX.","I(x) Net Zero"
"INX","I-nexus Global."
"I3E","I3 Energy"
"IDOX","Idox Group"
"IKA","Ilika Plc"
"IGE","Image Scan Holdings"
"IMM","Immupharma"
"IPX","Impax Asset Management"
"IPEL","Impellam Group"
"INHC","Induction Heal."
"ING","Ingenta"
"INSG","Insig Ai Plc"
"SPEC","Inspecs Group"
"IHC","Inspiration Hlt"
"INSE","Inspired"
"INSP","Inspirit Energy"
"IUG","Intelligent Ultrasound"
"IGP","Intercede"
"IES","Invinity Energy"
"IOF","Iofina"
"IOM","Iomart"
"IQE","IQE"
"IQG","Iqgeo"
"IRON","Ironveld"
"ITX","Itaconix Plc"
"ITIM","Itim Grou"
"ITM","Itm Power"
"IXI","Ixico"
"JSE","Jadestone Energy"
"JHD","James Halstead"
"JAN","Jangada Mines"
"JIM","Jarvis Securities"
"JWNG","Jaywing"
"JOG","Jersey Oil&amp;gas"
"JET2","Jet2"
"JSG","Johnson Service"
"JNEO","Journeo"
"JLP","Jubilee Metals"
"JDG","Judges Scientific"
"KDR","Karelian"
"KAT","Katoro Gold"
"KZG","Kazera Global"
"KEFI","Kefi Gold"
"KRS","Keras Res"
"KEYS","Keystone Law G."
"KWS","Keywords Studios Plc"
"KIBO","Kibo Energy"
"KWG","Kingswood H."
"KINO","Kinovo Plc"
"KIST","Kistos Holdings"
"KITW","Kitwave"
"KGH","Knights Group ."
"KOD","Kodal Minerals"
"KOO","Kooth Plc"
"KP2","Kore Potash"
"KMK","Kromek"
"LND","Landore"
"LOGP","Lansdowne Oil"
"LTHM","Latham Timber"
"LBG","LBG Media"
"LTG","Learning Technologies Group"
"LINV","Lendinvest"
"LEX","Lexington Gold"
"LIB","Libertine Hold"
"LIFS","Lifesafe Hldg"
"LST","Light Science"
"LIKE","Likewise Grp"
"LIT","Litigation Cap."
"LDG","Logistics Dev"
"LOK","Lok N Store"
"LBE","Longboat Energy"
"LOOP","Loopup Group"
"LORD","Lords Grp Tr"
"LGRS","Loungers Plc"
"LPA","Lpa"
"LLAI","Lunglife Ai"
"MPE","M P Evans"
"WINK","M Winkworth"
"SAA","M&amp;C Saatchi"
"MTEC","Made Tech"
"MAI","Maintel"
"MLVN","Malvern Intl"
"MANO","Manolete Partn."
"MFX","Manx Financial"
"MAC","Marechale Cap."
"MRK","Marks Electric"
"MRL","Marlowe"
"MTW","Mattioli Woods"
"MXCT","MaxCyte"
"MCM","Mc Mining"
"MDZ","Mediazest"
"MPL","Mercantile Ports &amp; Logistics"
"MERC","Mercia Asset"
"MTL","Metals Exploration"
"MET1","Metals One"
"MBH","Michelmersh Brick Holdings"
"SAAS","Microlise Grp"
"MIDW","Midwich Group"
"MIND","Mind Gym Plc"
"MFAI","Mindflair"
"MAFL","Mineral &amp; Fin"
"MIN","Minoan"
"MIRI","Mirriad Advertising"
"MKA","Mkango Res"
"MOS","Mobile Streams"
"MBT","Mobile Tornado"
"MBO","Mobilityone"
"MEN","Molecular Enrgy"
"MAB1","Mortgage Advice Bureau"
"MSMN","Mosman Oil Gas"
"MTC","Mothercare"
"MPAC","Mpac Group Plc"
"MSI","Ms Intl."
"MWE","Mti Wireless"
"MMAG","Musicmagpie"
"MYX","Mycelx Di"
"MHC","Myhlth Chck"
"N4P","N4 Pharma Plc"
"NAH","Nahl Group"
"WINE","Naked Wine"
"NET","Netcall"
"NWT","Newmark Security"
"NFG","Next 15 Group"
"NXQ","Nexteq"
"NEXS","Nexus Infrastr."
"NEXN","Nexxen Int Ltd"
"NICL","Nichols plc"
"NIOX","Niox Group"
"NBB","Norman Broadb"
"NAR","Northamber"
"CODE","Northcoders Grp"
"NTBR","Northern Bear"
"NTOG","Nostra Terra"
"NCYT","Novacyt"
"NWF","Nwf"
"OHT","Ocean Harvest T"
"ONC","Oncimmune"
"OBI","Ondine Biomed"
"OMIP","One Media"
"ONWD","Onward Opps"
"OPG","Opg Power"
"OPTI","OptiBiotix Health"
"ORCP","Oracle Power"
"ORCA","Orcadian Engy"
"ORCH","Orchard Funding"
"ORR","Oriole"
"OMI","Orosur Mining"
"OVB","Ovoca Bio"
"OBD","Oxford Biodyn"
"OMG","Oxford Metrics"
"PAF","Pan African"
"PANR","Pantheon Res"
"PAT","Panthera Res."
"PMG","Parkmead"
"PCIP","Pci-pal"
"PEB","Pebble Beach"
"PEEL","Peel Hunt"
"PEN","Pennant International"
"PGH","Personal Group"
"PEG","Petards"
"PET","Petrel Resources"
"MATD","Petro Matad"
"PTAL","PetroTal"
"PXC","Phoenix Copper."
"PHSC","PHSC"
"PYC","Physiomics"
"PIP","PipeHawk"
"PHC","Plant Health"
"POS","Plexus"
"POLR","Polar Capital"
"POLX","polarean"
"POLB","Poolbeg Pharma"
"PMP","Portmeirion"
"POW","Power Metal"
"PHE","Powerhouse Ener"
"PREM","Premier African Minerals"
"PMI","Premier Miton"
"PRES","Pressure Tech"
"PRIM","Primorus Inv."
"TPFG","Propty Franchis"
"PXEN","Prospex Eng"
"PRM","Proteome"
"PPS","Proton Mtr Pwr"
"PXS","Provexis"
"QED","Quadrise"
"QBT","Quantum Block"
"QTX","Quartix Tech"
"QUIZ","Quiz"
"RQIH","R&amp;Q Insurance"
"RAI","Ra Internation."
"RFX","Ramsdens Hldgs"
"RBGP","Rbg Holdings"
"RBD","Reabold Resources"
"REAT","React Group"
"RRR","Red Rock Resources"
"RCN","Redcentric"
"RLE","REI"
"RENX","Renalytix Plc"
"RENE","Reneuron"
"RNWH","Renew Holdings"
"RNO","Renold"
"RST","Restore"
"RBG","Rev Bars"
"RGO","Riverfort"
"ROAD","Roadside Real"
"RBN","Robinson"
"RKH","Rockhopper"
"RFG","Roebuck Food"
"RDT","Rosslyn Data"
"RTC","Rtc Grp."
"RUA","Rua Life Sci."
"RWS","RWS Holdings"
"SNT","Sabien Tech."
"SSTY","Safestay"
"SAR","Sareum"
"SAV","Savannah Resources"
"SCLP","Scancell Holdings"
"SAG","Science Group"
"SIS","Science Sprt"
"SCIR","Scirocco Energy"
"SDI","SDI Group"
"SDX","SDX Energy"
"SEED","Seed Innov"
"SEEN","Seeen"
"SEE","Seeing Machines"
"SRB","Serabi"
"SQZ","Serica Energy"
"SENX","Serinus Energy"
"SHG","Shanta Gold"
"SWG","Shearwater"
"STX","Shield Thera"
"SHOE","Shoe Zone"
"SKA","Shuka Minerals"
"SRC","Sigmaroc."
"SBDS","Silver Bullet"
"SAE","Simec Atlantis"
"SKL","Skillcast"
"SBTX","Skinbiotherap."
"SMS","Smart Metering Systems"
"SMRT","Smartspace"
"SDG","Sndrsn Dsn"
"SFT","Software Circle"
"SOLI","Solid State"
"SOM","Somero"
"SND","Sondrel Plc"
"SOS","Sosandar"
"SOU","Sound Energy"
"SOUC","Southern Energy"
"SAL","SpaceandPeople"
"SPSY","Spectra (unres)"
"SPR","Springfield Pr."
"SRT","Srt Marine Sys."
"STAF","Staffline"
"STAR","Star Energy"
"STCM","Steppe Cement"
"STM","Stm Grp."
"SML","Strategic Minerals"
"STG","Strip Tinning"
"KETL","Strix"
"SRES","Sunrise Res"
"SUP","Supreme Plc"
"SCE","Surface Transforms"
"SUN","Surgical Innovations"
"SLP","Sylvania Platinum"
"SYM","Symphony Env."
"SNG","Synairgen"
"SNX","Synectics"
"SYN","Synergia Energy"
"SYS","Sysgroup"
"SYS1","System1 Group"
"TRAC","T42 Iot Track."
"TND","Tandem Group"
"TAST","Tasty"
"TAM","Tatton Asset Management"
"TAVI","Tavistock"
"TIG","Team Internet"
"TM17","Team17"
"TEK","TekCapital"
"TGP","Tekmar Group P."
"TENG","Ten Life"
"TERN","Tern"
"TYM","Tertiary Minerals"
"TMG","The Mission Group"
"PEBB","The Pebble Gro."
"THR","Thor Energy"
"THX","Thor Explor"
"TFW","Thorpe"
"THRU","Thruvision Grp"
"TIA","Tialis Essen It"
"TIME","Time Finance"
"TMO","Time Out"
"TBLD","Tinybuild Inc"
"TRX","Tissue Regenix Group"
"TON","Titon"
"TLOU","Tlou Energy"
"TOM","Tomco Energy"
"MEX","Tortilla Mexic"
"TLY","Totally"
"TST","Touchstar Plc"
"TXP","Touchstone Exploration"
"TRP","Tower Resources"
"TPX","Tpximpact Hldg"
"TRCS","Tracsis"
"TRAK","Trakm8 Hldgs"
"TRT","Transense"
"TRLS","Trellus Health."
"TRB","Tribal Grp."
"TRR","Trident Royalties"
"TRIN","Trinity"
"TSTL","Tristel"
"TRU","Trufin Plc"
"TUN","Tungsten West"
"UKOG","Uk Oil &amp; Gas"
"UJO","Union Jack"
"UPR","Uniphar"
"UOG","United Oil&amp;gas"
"URU","Uru Metals"
"VAL","ValiRx"
"VANL","Van Elle"
"VARE","Various Eat."
"VAST","Vast Res"
"VCAP","Vector Capital"
"VELA","Vela Technologies"
"VEL","Velocity Comp"
"VLG","Venture Life"
"VRCI","Verici Dx"
"VRS","Versarien"
"VTU","Vertu"
"VNET","Vianet Grp"
"VCP","Victoria"
"VIC","Victorian Plumbing"
"VINO","Virgin Wines"
"VLX","Volex"
"VLE","Volvere"
"W7L","Warpaint London"
"WATR","Water Intel."
"WJG","Watkin Jones"
"WEB","Webis"
"WKOF","Weiss Korea Opp"
"WSG","Westminster Group"
"WTE","Westmount Engy."
"WHI","WHIreland"
"WPHO","Windar Photo"
"WNWD","Windward"
"WSBN","Wishbone"
"WBI","Woodbois"
"WYN","Wynnstay"
"XSG","Xeros Tech"
"XLM","Xlmedia"
"XPF","Xp Factory"
"XTR","Xtract"
"YCA","Yellow Cake"
"YOU","YouGov"
"YNGA","Young &amp; Co's Brewery"
"YNGN","Young &amp; Co's Brewery"
"YU.","Yu Energy"
"ZIOC","Zanaga Iron"
"ZED","Zenova Grp"
"ZPHR","Zephyr Energy"
"ZIN","Zinc Media"
"ZNWD","Zinnwald Lithium"
"ZOO","Zoo Digital"
  "ZYT","Zytronic"`,
      ftse250: `"TIDM","Company"
"3IN","3i Infrastructure"
"FOUR","4Imprint"
"ASL","Aberforth Smaller Companies Trust Plc"
"ABDN","Abrdn"
"APEO","abrdn Private Equity Opportunities Trust"
"AJB","AJ Bell"
"ATST","Alliance Trust"
"ATT","Allianz Technology Trust"
"AO.","Ao World"
"APAX","Apax Global Alpha"
"ASCL","Ascential"
"ASHM","Ashmore"
"DGN","Asia Dragon"
"AGR","Assura"
"AML","Aston Martin Lagonda"
"ATG","Auction Technology Group"
"AGT","AVI Global Trust"
"BAB","Babcock"
"USA","Baillie Gifford"
"BGFD","Baillie Gifford Japan Trust PLC"
"BAKK","Bakkavor"
"BCPT","Balanced Commercial Property Trust"
"BBY","Balfour Beatty"
"BCG","Baltic Classifieds Group"
"BGEO","Bank Of Georgia Group"
"BNKR","Bankers Investment Trust"
"BAG","Barr (A.G.)"
"BBGI","BBGI Global Infrastructure"
"BBH","Bellevue Health"
"BWY","Bellway"
"BHMG","BH Macro GBP"
"BYG","Big Yellow"
"BRGE","BlackRock Greater Europe Investment Trust"
"BRSC","BlackRock Smaller Companies Trust PLC"
"BRWM","BlackRock World Mining Trust plc"
"BSIF","Bluefield Solar"
"BOY","Bodycote"
"BREE","Breedon"
"BPT","Bridgepoint"
"BLND","British Land"
"BVIC","Britvic"
"BYIT","Bytes Tech"
"CCR","C&amp;C Group"
"CLDN","Caledonia"
"CGT","Capital Gearing Trust"
"CCL","Carnival"
"CEY","Centamin PLC"
"CHG","Chemring"
"CTY","City Of London Investment"
"CKN","Clarkson"
"CBG","Close Bros"
"COA","Coats"
"CCC","Computacenter"
"CWK","Cranswick"
"CRST","Crest Nicholson"
"CURY","Currys"
"DARK","Darktrace"
"DLN","Derwent London"
"DLG","Direct Line"
"DSCV","DiscoverIE"
"DEC","Diversified Energy"
"DOM","Dominos"
"DWL","Dowlais"
"DOCS","Dr. Martens"
"DRX","Drax"
"DNLM","Dunelm"
"EZJ","easyJet"
"EDIN","Edinburgh Investment Trust PLC"
"EWI","Edinburgh Worldwide"
"ELM","Elementis"
"ESP","Empiric"
"ENOG","Energean Oil &amp; Gas"
"ESNT","Essentra"
"EOT","Euro Opps Tr."
"ESCT","European Small."
"FDM","FDM Group"
"FXPO","Ferrexpo"
"FSV","Fidelity"
"FCSS","Fidelity China Special Situations PLC"
"FEML","Fidelity E.m.ld"
"FEV","Fidelity European Values"
"FGT","Finsbury Growth"
"FGP","Firstgroup"
"FSFL","Foresight Solar Fund"
"FSG","Foresightgr"
"FUTR","Future"
"GAW","Games Workshop"
"GCP","GCP Infrastructure Investments"
"GEN","Genuit Group"
"GNS","Genus"
"GSCT","Glb Sml Co Trst"
"GPE","GPE"
"GFTU","Grafton Group"
"GRI","Grainger plc"
"UKW","Greencoat UK Wind"
"GRG","Greggs"
"HMSO","Hammerson"
"HBR","Harbour Energy"
"HVPE","HarbourVest Private Equity"
"HL.","Hargreaves Lansdown"
"HAS","Hays"
"HTWS","Helios Towers"
"HSL","Henderson Smaller Companies Trust"
"HRI","Herald"
"HGT","HgCapital Trust plc"
"HICL","HICL Infrastructure"
"HILS","Hill &amp; Smith"
"HFG","Hilton Foods"
"SONG","Hipgnosis Song."
"HSX","Hiscox"
"HOC","Hochschild"
"BOWL","Hollywood Bwl"
"HTG","Hunting"
"IBST","Ibstock"
"ICGT","ICG Enterprise Trust"
"IGG","Ig Group Holdings"
"IEM","Impax Asset Management"
"INCH","Inchcape"
"INDV","Indivior"
"IHP","IntegraFin Holdings"
"IDS","International Distributions Services"
"INPP","International Public Partnerships"
"INVP","Investec"
"IPO","Ip Group"
"ITH","Ithaca Energy"
"ITV","ITV"
"IWG","IWG"
"JLEN","JLEN"
"JMAT","Johnson Matthey"
"JAM","JPMorgan American"
"JMG","JPMorgan Emerging Markets Investment Trust"
"JEDT","JPMorgan European Discovery Trust"
"JGGI","JPMorgan Global Growth &amp; Income"
"JII","JPMorgan Indian"
"JFJ","JPMorgan Japanese"
"JTC","Jtc Plc"
"JUP","Jupiter Fund Management"
"JUST","Just Group"
"KNOS","Kainos Group"
"KLR","Keller"
"LRE","Lancashire Holdings"
"LWDB","Law Debenture"
"LMP","LondonMetric"
"EMG","Man"
"MSLH","Marshalls"
"MEGP","ME Group"
"MRC","Mercantile Investment Trust PLC"
"MRCH","Merchants Trust"
"MAB","Mitchells &amp; Butlers"
"MTO","Mitie"
"MCG","Mobico Group"
"MONY","Moneysupermarket.Com"
"MNKS","Monks Inv"
"MOON","Moonpig Gr"
"MGAM","Morgan Advanced Materials"
"MGNS","Morgan Sindall Group"
"MUT","Murray Income Trust"
"MYI","Murray International"
"NBPE","Nb Priv. Eqty"
"NETW","Network International"
"NESF","NextEnergy Solar"
"N91","Ninety One"
"NAS","North Atl.smlr"
"ORIT","Octopus Energy"
"OSB","OneSavings Bank"
"OXIG","Oxford Instruments"
"PHI","Pacific Horizon"
"PAGE","PageGroup"
"PIN","Pantheon International"
"PAG","Paragon Group"
"PNN","Pennon"
"PNL","Personal Assets Trust"
"PHLL","Petershill"
"PETS","Pets at home"
"PTEC","Playtech"
"PLUS","Plus500"
"PCT","Polar Capital Technology Trust"
"PPH","Pphe Hotel"
"PFD","Premier Foods"
"PHP","Primary Health"
"PRTC","PureTech"
"PZC","Pz Cussons"
"QQ.","Qinetiq"
"QLT","Quilter"
"RAT","Rathbone"
"REDD","Redde Northgate"
"RDW","Redrow"
"TRIG","Renewables Infrastructure Group"
"RSW","Renishaw"
"RHIM","RHI Magnesita"
"RCP","RIT Capital Partners"
"ROR","Rotork"
"RICA","Ruffer"
"SAFE","Safestore"
"SVS","Savills"
"SDP","Schroder AsiaPacific Fund"
"SOI","Schroders"
"SAIN","Scot.amer.inv."
"SEIT","Sdcl Energy Ef."
"SNR","Senior"
"SEQI","Sequoia Economic Infrastructure Fund"
"SRP","Serco"
"SHC","Shaftesbury Capital"
"SRE","Sirius Real Estate"
"SSON","Smithson Invest"
"SCT","Softcat"
"SXS","Spectris"
"SPI","Spire Healthcare"
"SPT","Spirent"
"SSPG","SSP Group"
"STEM","SThree"
"SUPR","Supermarket Income"
"SYNC","Syncona"
"THRL","Target Healthc."
"TATE","Tate &amp; Lyle"
"TBCG","TBC Bank Group"
"TEP","Telecom Plus"
"TMPL","Temple Bar Investment Trust"
"TEM","Templeton Emerging Markets"
"THRG","Throgmorton Trust"
"TIFS","TI Fluid Systems"
"TCAP","TP ICAP"
"TRY","TR Property Investment Trust"
"TRN","Trainline"
"TPK","Travis Perkins"
"BBOX","Tritax Big Box"
"EBOX","Tritax Eurobox"
"TRST","Trustpilot"
"TUI","TUI AG"
"TLW","Tullow Oil"
"TFIF","Twentyfour Inc"
"TYMN","Tyman"
"UKCM","UK Commercial Property Trust"
"SHED","Urban Logistics"
"VSVS","Vesuvius"
"VCT","Victrex"
"VEIL","Vietnam Enterprise Investments"
"VOF","VinaCapital Vietnam Opportunity Fund"
"VMUK","Virgin Money Uk"
"VTY","Vistry Grp"
"FAN","Volution Group PLS"
"WPS","Wag Payment"
"WOSG","Watches Switz"
"JDW","Wetherspoon (J.D)"
"SMWH","Wh Smith"
"WTAN","Witan"
"WIZZ","Wizz Air"
"WG.","Wood Group (J)"
"WKP","Workspace"
"WWH","Worldwide Healthcare Trust"`,
    },
  };
}


export async function getCompanyNews() {
  async function fetchNewsJSON() {
    const response = await fetch(
      "http://localhost:3000/api/share-research?search='Ftse latest'"
    );
    const news = await response.json();
    return news;
  }

  const news = await fetchNewsJSON();

  return news;
}

export async function getShareQuote(ticker) {
  async function fetchQuoteJSON() {
    const response = await fetch(
      `http://localhost:3000/api/yahoo?symbol=${ticker}.l`
    );
    const quote = await response.json();
    return quote;
  }

  const quote = await fetchQuoteJSON();

  return quote;
}